Updates
ChildrenOfYahweh/Kematian-Stealer pull request #224
Opened 2024-05-21 23:41 UTC by Chainski

- [x] Updated ANTI-VM checks

2024-05-21 23:46 UTC, KDot227 requested changes

2024-05-21 23:46 UTC, KDot227 commented on frontend-src/antivm.ps1
> +    if ($detectedProcesses -eq $null) {
Have it do the null first or else the powershell style checker screams at me.

2024-05-21 23:50 UTC, Chainski commented on frontend-src/antivm.ps1
> +    if ($detectedProcesses -eq $null) {
Ok I wondered why you had it backwards. give me a sec

2024-05-21 23:52 UTC, Chainski commented on frontend-src/antivm.ps1
> +    if ($detectedProcesses -eq $null) {
Done !

2024-05-22 00:14 UTC, Chainski reviewed
Changes made

2024-05-22 03:45 UTC, merged